dragonfly:
  interval: 10000
  chatId: -1001288425638
  creatorId: 664242935
  name: Lecia
  tg: true
server:
  port: 8080
spring:
  data:
    mongodb:
      database: asl
  main:
    lazy-initialization: true