dragonfly:
  interval: 10000
  chatId: -1001288425638
  creatorId: 664242935
  name: Lecia
  tg: false
  emails:
    - zdkscope01@outlook.com
    - zdkscope02@outlook.com
    - zdkscope03@outlook.com
server:
  port: 8080
spring:
  data:
    mongodb:
      database: asl
  main:
    lazy-initialization: true